from typing import Callable, Dict, List

from . import (
    ai,
    ask,
    build,
    cache,
    check,
    clean,
    debug,
    deploy,
    dev,
    docs,
    doctor,
    explain,
    firmware,
    fix,
    generate,
    headers,
    history,
    imports,
    init,
    kit,
    lint,
    module,
    package,
    pkg,
    platforms,
    release,
    replay,
    run,
    selfcmd,
    serve,
    setup,
    shell,
    studio,
    test,
    toolchain,
    tui,
    vcs,
    verify,
    why,
)

COMMANDS: Dict[str, Callable[[List[str]], int]] = {
    "init": init.execute,
    "build": build.execute,
    "check": check.execute,
    "status": vcs.execute_status,
    "commit": vcs.execute_commit,
    "push": vcs.execute_push,
    "pr": vcs.execute_pr,
    "hooks": vcs.execute_hooks,
    "release": release.execute,
    "ci": release.execute_ci,
    "sign": release.execute_sign,
    "run": run.execute,
    "fix": fix.execute,
    "generate": generate.execute,
    "ai": ai.execute,
    "serve": serve.execute,
    "setup": setup.execute,
    "self": selfcmd.execute,
    "shell": shell.execute,
    "studio": studio.execute,
    "tui": tui.execute,
    "clean": clean.execute,
    "deploy": deploy.execute,
    "debug": debug.execute,
    "dev": dev.execute,
    "debug-adapter": debug.execute_adapter,
    "doctor": doctor.execute,
    "docs": docs.execute,
    "test": test.execute,
    "package": package.execute,
    "ask": ask.execute,
    "explain": explain.execute,
    "size": firmware.execute_size,
    "flash": firmware.execute_flash,
    "verify-reproducible": verify.execute,
    "why": why.execute,
    "history": history.execute,
    "import": imports.execute,
    "diff-build": history.execute_diff,
    "cache": cache.execute,
    "module": module.execute,
    "pkg": pkg.execute,
    "sbom": pkg.execute_sbom,
    "lint": lint.execute,
    "kit": kit.execute,
    "migrate": lint.execute_migrate,
    "options": lint.execute_options,
    "toolchain": toolchain.execute,
    "platforms": platforms.execute,
    "headers": headers.execute,
    "replay": replay.execute,
}

__all__ = ["COMMANDS"]
