from typing import Callable, Dict, List

from . import (
    ask,
    build,
    cache,
    check,
    clean,
    deploy,
    doctor,
    explain,
    firmware,
    headers,
    history,
    init,
    kit,
    lint,
    module,
    package,
    pkg,
    platforms,
    release,
    replay,
    run,
    test,
    toolchain,
    vcs,
    why,
)

COMMANDS: Dict[str, Callable[[List[str]], int]] = {
    "init": init.execute,
    "build": build.execute,
    "check": check.execute,
    "status": vcs.execute_status,
    "commit": vcs.execute_commit,
    "push": vcs.execute_push,
    "pr": vcs.execute_pr,
    "hooks": vcs.execute_hooks,
    "release": release.execute,
    "ci": release.execute_ci,
    "sign": release.execute_sign,
    "run": run.execute,
    "clean": clean.execute,
    "deploy": deploy.execute,
    "doctor": doctor.execute,
    "test": test.execute,
    "package": package.execute,
    "ask": ask.execute,
    "explain": explain.execute,
    "size": firmware.execute_size,
    "flash": firmware.execute_flash,
    "why": why.execute,
    "history": history.execute,
    "diff-build": history.execute_diff,
    "cache": cache.execute,
    "module": module.execute,
    "pkg": pkg.execute,
    "sbom": pkg.execute_sbom,
    "lint": lint.execute,
    "kit": kit.execute,
    "migrate": lint.execute_migrate,
    "options": lint.execute_options,
    "toolchain": toolchain.execute,
    "platforms": platforms.execute,
    "headers": headers.execute,
    "replay": replay.execute,
}

__all__ = ["COMMANDS"]
