"""`charpente generate` -- project files for other tools: compile_commands.json, build.ninja, CMakeLists.txt, a Visual Studio solution."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Dict, List

from .. import fsutil
from ..core.planner import plan_workspace
from ..generators import cmake as cmake_gen
from ..generators import ninja as ninja_gen
from ..generators import vs as vs_gen
from ._common import CommandError, load, toolchain_for
from ._session import add_engine_args

MARKER = "Generated by `charpente generate"
FORMATS = {
    "compile-commands": "compile_commands.json for clangd and other tools, with the exact arguments the engine uses (verified with clangd)",
    "ninja": "build.ninja: the engine's action plan for Ninja (verified with Ninja)",
    "cmake": "CMakeLists.txt from the workspace model (verified by configuring and building it with CMake)",
    "vs": "a Visual Studio solution and one Makefile project per target that calls charpente (NOT opened in Visual Studio: unverified)",
    "xcode": "an Xcode project (not implemented: it needs a Mac to be checked)",
}


def _refuse_foreign(path: Path, force: bool) -> None:
    """Never overwrite a file Charpente did not write (a hand-written CMakeLists.txt, for example)."""
    if path.exists() and not force:
        head = path.read_text(encoding="utf-8", errors="replace")[:400]
        if MARKER not in head:
            raise CommandError("CH8027", what=path.name, detail=f"{path} exists and was not generated by Charpente (use --force to overwrite it, or --out to write elsewhere)")


def _write(files: Dict[str, str], folder: Path, force: bool) -> List[Path]:
    folder.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in files.items():
        target = folder / name
        _refuse_foreign(target, force)
        fsutil.write_text(target, text, newline="")
        written.append(target)
    return written


def execute(args: List[str]) -> int:
    parser = argparse.ArgumentParser(prog="charpente generate", description="Generate project files for other tools.")
    parser.add_argument("format", nargs="?", choices=list(FORMATS), help="What to generate")
    parser.add_argument("--file", help="Path to the .charpente workspace file")
    parser.add_argument("--out", help="Folder to write into (default: the project folder)")
    parser.add_argument("--config", default="Debug", choices=["Debug", "Release"])
    parser.add_argument("--force", action="store_true", help="Overwrite existing files that were not generated by Charpente")
    parser.add_argument("--list", action="store_true", help="List the formats and what each is verified against")
    add_engine_args(parser, output=False)
    parsed = parser.parse_args(args)
    if parsed.list or not parsed.format:
        for name, text in FORMATS.items():
            print(f"  {name:<17} {text}")
        return 0
    if parsed.format == "xcode":
        raise CommandError("CH8027", what="an Xcode project", detail="not implemented (it cannot be checked without a Mac); use `charpente generate cmake` and CMake's Xcode generator")

    workspace = load(parsed.file, parsed.opt)
    folder = Path(parsed.out).resolve() if parsed.out else Path(workspace.root)
    if parsed.format == "compile-commands":
        from ..serve.rpc import RpcError
        from ..serve.state import ServerState

        state = ServerState(Path(workspace.root), parsed.file)
        try:
            entries = state.compile_commands(parsed.config)
        except RpcError as exc:
            raise CommandError("CH8027", what="compile_commands.json", detail=exc.message) from exc
        folder.mkdir(parents=True, exist_ok=True)
        target = folder / "compile_commands.json"
        target.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {target} ({len(entries)} files).")
        return 0
    if parsed.format == "ninja":
        target_os, toolchain = toolchain_for(parsed, workspace)
        plan = plan_workspace(workspace, toolchain, target_os, config=parsed.config)
        for name, error in plan.errors.items():
            print(f"charpente: warning: {name} is not in build.ninja: {error.message}")
        text = ninja_gen.render(plan, Path(workspace.root), windows=os.name == "nt")
        written = _write({"build.ninja": text}, folder, parsed.force)
        print(f"Wrote {written[0]} ({len(plan.graph)} actions). Build with `ninja -C {folder}`.")
        return 0
    if parsed.format == "cmake":
        written = _write({"CMakeLists.txt": cmake_gen.render(workspace)}, folder, parsed.force)
        print(f"Wrote {written[0]}. Configure with `cmake -S {folder} -B build`.")
        return 0
    written = _write(vs_gen.render(workspace), folder, parsed.force)
    print(f"Wrote {len(written)} files in {folder}: open {workspace.name}.sln. (Generated from the documented formats; not checked in Visual Studio.)")
    return 0
