"""`charpente.lock`: the exact packages a workspace builds with.

    # charpente.lock -- generated by `charpente pkg install`; commit it.
    lock_version = 1

    [[package]]
    name = "fmt"
    version = "10.2.1"
    recipe_sha256 = "..."       # the exact recipe bytes
    source_url = "https://..."
    source_sha256 = "..."       # the exact archive
    dependencies = []
    requested_by = ["workspace"]

With a lock file, every machine resolves to the same versions and verifies the
same digests, so builds are reproducible. Editing `ws.requires(...)` does not
change what is built until you run `charpente pkg install` again.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from .. import _toml
from ..errors import ChError

LOCK_NAME = "charpente.lock"
LOCK_VERSION = 1


@dataclass(frozen=True)
class LockedPackage:
    name: str
    version: str
    recipe_sha256: str
    source_url: str
    source_sha256: str
    dependencies: "tuple[str, ...]" = ()
    requested_by: "tuple[str, ...]" = ()


@dataclass
class Lock:
    packages: Dict[str, LockedPackage] = field(default_factory=dict)

    def dumps(self) -> str:
        lines = ["# charpente.lock -- generated by `charpente pkg install`; commit it.",
                 f"lock_version = {LOCK_VERSION}", ""]
        for name in sorted(self.packages):
            p = self.packages[name]
            lines += [
                "[[package]]",
                f"name = {json.dumps(p.name)}",
                f"version = {json.dumps(p.version)}",
                f"recipe_sha256 = {json.dumps(p.recipe_sha256)}",
                f"source_url = {json.dumps(p.source_url)}",
                f"source_sha256 = {json.dumps(p.source_sha256)}",
                f"dependencies = {json.dumps(list(p.dependencies))}",
                f"requested_by = {json.dumps(list(p.requested_by))}",
                "",
            ]
        return "\n".join(lines)

    def get(self, name: str) -> Optional[LockedPackage]:
        return self.packages.get(name)

    def versions(self) -> Dict[str, str]:
        return {n: p.version for n, p in self.packages.items()}


def loads(text: str, path: str = LOCK_NAME) -> Lock:
    try:
        data = _toml.loads(text)
    except _toml.TOMLDecodeError as exc:
        raise ChError("CH6006", path=path, detail=f"not valid TOML: {exc}") from exc
    if data.get("lock_version") != LOCK_VERSION:
        raise ChError("CH6006", path=path, detail=f"unsupported lock_version {data.get('lock_version')!r}")
    lock = Lock()
    for raw in data.get("package", []):
        try:
            pkg = LockedPackage(
                name=str(raw["name"]), version=str(raw["version"]), recipe_sha256=str(raw["recipe_sha256"]),
                source_url=str(raw["source_url"]), source_sha256=str(raw["source_sha256"]),
                dependencies=tuple(str(d) for d in raw.get("dependencies", [])),
                requested_by=tuple(str(r) for r in raw.get("requested_by", [])))
        except KeyError as exc:
            raise ChError("CH6006", path=path, detail=f"a [[package]] lacks {exc}") from exc
        lock.packages[pkg.name] = pkg
    return lock


def load(root: Path) -> Optional[Lock]:
    path = Path(root) / LOCK_NAME
    if not path.exists():
        return None
    return loads(path.read_text(encoding="utf-8"), str(path))


def save(root: Path, lock: Lock) -> Path:
    path = Path(root) / LOCK_NAME
    path.write_text(lock.dumps(), encoding="utf-8", newline="\n")
    return path


def matches_requirements(lock: Lock, requires: List[str]) -> bool:
    """True if every direct requirement is satisfied by the locked version."""
    from .recipe import constraint_of

    for spec in requires:
        name, constraint = constraint_of(spec)
        pkg = lock.get(name)
        if pkg is None or not constraint.matches(pkg.version):
            return False
    return True
