"""`build.ninja` from Charpente's action plan: the same commands the engine would run, for people who keep Ninja as their build tool.

Every action becomes one rule and one build edge. Dependencies between actions are the files that feed each other (objects into the link),
header dependencies use Ninja's own depfile support (`deps = gcc` for `-MMD -MF`, `deps = msvc` for `/showIncludes`). Paths in build statements are relative to
the folder of `build.ninja` (which is the project root), so no drive letter needs escaping; commands carry the absolute paths the engine uses.

Unlike `charpente build`, Ninja does not cache by content, does not track the environment or the compiler's identity, and does not re-run an action
when only its command line changed in a way it cannot see: it is a projection of the plan, not a second engine.
"""
from __future__ import annotations

import shlex
from pathlib import Path
from typing import Dict, List

from ..core.actions import DEP_GNU, DEP_MSVC, Action
from ..core.planner import Plan
from ..core.process import windows_command_line


def _rel(path: Path, root: Path) -> str:
    try:
        text = path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        text = path.resolve().as_posix()
    return _escape_path(text)


def _escape_path(text: str) -> str:
    return text.replace("$", "$$").replace(" ", "$ ").replace(":", "$:")


def _escape_value(text: str) -> str:
    return text.replace("$", "$$")


def command_line(action: Action, windows: bool) -> str:
    argv = list(action.argv)
    if windows:
        text = windows_command_line(argv)
        prefix = "".join(f"set {name}={value}&& " for name, value in action.env)
    else:
        text = " ".join(shlex.quote(a) for a in argv)
        prefix = "".join(f"{name}={shlex.quote(value)} " for name, value in action.env)
    return prefix + text


def render(plan: Plan, root: Path, *, windows: bool) -> str:
    lines: List[str] = ["# Generated by `charpente generate ninja`. Regenerate after changing the .charpente file.", "ninja_required_version = 1.7", ""]
    graph = plan.graph
    number: Dict[str, int] = {}
    for action_id in graph.topological_order():
        action = graph.actions[action_id]
        number[action_id] = len(number)
        rule = f"a{number[action_id]}"
        lines.append(f"rule {rule}")
        lines.append(f"  command = {_escape_value(command_line(action, windows))}")
        lines.append(f"  description = {_escape_value(action.description or action.id)}")
        if action.dep_format == DEP_GNU and action.depfile is not None:
            lines.append(f"  depfile = {_rel(action.depfile, root)}")
            lines.append("  deps = gcc")
        elif action.dep_format == DEP_MSVC:
            lines.append("  deps = msvc")
        outputs = " ".join(_rel(o, root) for o in action.outputs)
        inputs = " ".join(_rel(i, root) for i in action.inputs)
        implicit = sorted({_rel(o, root) for dep in graph.deps[action_id] for o in graph.actions[dep].outputs} - {_rel(i, root) for i in action.inputs})
        lines.append(f"build {outputs}: {rule} {inputs}" + (" | " + " ".join(implicit) if implicit else ""))
        lines.append("")
    finals = [plan.outputs[name] for name in plan.order if name in plan.outputs]
    for name in plan.order:
        if name in plan.outputs:
            lines.append(f"build {_escape_path(name)}: phony {_rel(plan.outputs[name], root)}")
    if finals:
        lines.append("default " + " ".join(_rel(o, root) for o in finals))
    return "\n".join(lines).rstrip() + "\n"
