"""The words of the console interface, in English and French. Both tables must have exactly the same keys (a test checks it, and that every key used exists)."""
from __future__ import annotations

from typing import Dict

TIP_COUNT = 6
GUIDE_LINES = 8
HELP_LINES = 13

YES = {"en": ("y", "yes"), "fr": ("o", "oui", "y", "yes")}
NO = {"en": ("n", "no"), "fr": ("n", "non", "no")}

EN: Dict[str, str] = {
    "tagline": "the C/C++ build system",
    "bye": "See you soon.",
    "footer.keys": "{ud} move   Enter choose   the key beside a row: shortcut   Esc back   Ctrl+C leave",
    "footer.line": "Type the number or letter of a row, then Enter.   q: back",
    "prompt.choice": "Your choice: ",
    "prompt.unknown": "'{answer}' is not in the list.",
    "prompt.required": "An answer is needed here.",
    "prompt.press_enter": "Press Enter to go back to the menu...",
    "prompt.yes_no_default_yes": "[Y/n]",
    "prompt.yes_no_default_no": "[y/N]",
    "ago.seconds": "{n} s ago",
    "ago.minutes": "{n} min ago",
    "ago.hours": "{n} h ago",
    "ago.days": "{n} d ago",
    "dash.title": "Where you are",
    "dash.folder": "Folder",
    "dash.last": "Last build",
    "dash.mode": "Working mode",
    "dash.compiler": "Compiler",
    "dash.native": "this machine",
    "dash.targets": "{n} target(s)",
    "dash.no_build": "none yet",
    "dash.succeeded": "succeeded",
    "dash.failed": "failed",
    "dash.no_project": "No project in this folder",
    "dash.no_compiler": "none found (choose \"Prepare this machine\")",
    "dash.untrusted": "This project file has not been approved yet: Charpente will ask you before running it.",
    "dash.untrusted_short": "not approved yet",
    "dash.error": "The project file cannot be read: {detail}",
    "dash.error_short": "project file has an error",
    "dash.ambiguous": "Several project files here: {detail}",
    "group.start": "Start",
    "group.more": "More",
    "group.build": "Build and run",
    "group.project": "Your project",
    "group.tools": "Tools",
    "group.session": "This session",
    "item.create": "Create a new project",
    "hint.create": "Pick a template (program, library, game, Android app...)",
    "item.open": "Open an existing project",
    "hint.open": "Go to a folder that holds a .charpente file",
    "item.setup": "Prepare this machine",
    "hint.setup": "Finds what is missing (a compiler...) and offers to fix it",
    "hint.recommended": "Recommended:",
    "item.check_machine": "Check this machine",
    "hint.check_machine": "Compilers and tools found, platforms you can build",
    "item.guide": "Learn: the first steps",
    "hint.guide": "Five minutes to your first program",
    "item.build": "Build",
    "hint.build": "Compile the project ({mode})",
    "item.run": "Run",
    "hint.run": "Build if needed, then start a program",
    "reason.cross_run": "Programs built for {platform} cannot run on this machine.",
    "reason.fix_project": "Fix the project file first (the message is above).",
    "item.test": "Test",
    "hint.test": "Build and run the tests",
    "item.watch": "Rebuild on every change",
    "hint.watch": "Watches your files (Ctrl+C to stop)",
    "item.targets": "Targets and packages",
    "hint.targets": "What the project builds; libraries to add",
    "item.platform": "Target platform",
    "hint.platform": "Now: {platform}. Linux ARM, Android, web, microcontrollers...",
    "item.package": "Package",
    "hint.package": "A zip, an installer or an Android app to hand out",
    "item.check": "Quality check",
    "hint.check": "Format, warnings, secrets, tests before you commit",
    "item.doctor": "Diagnose and understand",
    "hint.doctor": "Explain an error, see why something rebuilt, history",
    "item.git": "Git",
    "hint.git": "Status, a checked commit, push",
    "item.cache": "Cache and cleaning",
    "hint.cache": "Free disk space, start from scratch",
    "item.studio": "Open Charpente Studio",
    "hint.studio": "The graphical interface in your browser",
    "item.tui": "Full-screen terminal interface",
    "hint.tui": "Targets and live build log (needs: pip install \"charpente[tui]\")",
    "item.mode": "Switch to {mode}",
    "hint.mode": "Now: {mode}. Release is optimised, Debug is for debugging",
    "mode.now": "Working mode is now {mode}.",
    "item.lang": "Langue : {other}",
    "lang.now": "Language: English.",
    "item.help": "Help and shortcuts",
    "hint.help": "How this menu works, the commands behind it",
    "item.quit": "Quit",
    "tag.unverified": "[not verified]",
    "create.title": "Create a new project",
    "create.subtitle": "Choose what to start from. Every template builds with the same commands.",
    "create.default_name": "my-project",
    "create.template": "Template: {template}",
    "create.name": "Project name (letters, digits, - and _)",
    "create.bad_name": "Start with a letter; then letters, digits, - or _ only.",
    "create.exists": "{folder} already exists: choose another name.",
    "create.summary": "A '{template}' project named '{name}' will be created in {folder}.",
    "create.confirm": "Create it?",
    "create.opened": "Project '{name}' created and opened. Try Build, then Run.",
    "open.title": "Open an existing project",
    "open.other": "Another folder...",
    "open.other_hint": "Type the path of a project folder",
    "open.path": "Folder of the project",
    "open.not_a_folder": "'{path}' is not a folder.",
    "open.opened": "Now working in {folder}.",
    "pick.target": "Which target?",
    "run.args": "Arguments for the program (Enter for none)",
    "watch.note": "Charpente will rebuild each time you save a file. Press Ctrl+C to come back.",
    "check.title": "Quality check",
    "check.fast": "Fast",
    "check.fast_hint": "Build, format, project file, secrets: seconds",
    "check.standard": "Standard",
    "check.standard_hint": "Adds warnings, static analysis and tests",
    "check.strict": "Strict",
    "check.strict_hint": "Adds sanitizers, coverage, licences, dependency audit",
    "package.title": "Package as...",
    "package.zip": "A zip archive of the program",
    "package.installer": "installer",
    "package.installer_hint": "An installer for this system (needs its packaging tool)",
    "package.apk": "A signed Android app",
    "targets.title": "Targets and packages",
    "targets.list": "Show the targets",
    "targets.list_hint": "What this project builds",
    "targets.none": "The project's targets are shown once it is approved and readable.",
    "targets.search": "Search a package",
    "targets.search_hint": "fmt, spdlog, nlohmann_json...",
    "targets.query": "What are you looking for",
    "targets.install": "Install the project's packages",
    "targets.install_hint": "Downloads and checks what the project requires",
    "targets.kits": "List the kits",
    "targets.kits_hint": "Ready-made sets of libraries",
    "targets.addkit": "Add a kit to the project",
    "targets.addkit_hint": "Graphics, game, network, embedded...",
    "platform.title": "Target platform",
    "platform.subtitle": "What you choose here applies to Build, Test, Package and Rebuild.",
    "platform.checking": "Looking at what this machine can build...",
    "platform.actions": "Actions",
    "platform.deploy": "Install on Android devices",
    "platform.deploy_hint": "Builds for every connected phone or emulator and starts the app",
    "platform.choose": "Build for",
    "platform.native": "This machine ({host})",
    "platform.native_hint": "The default",
    "platform.tier": "level {tier}",
    "platform.needs_toolchain": "Needs a toolchain: run \"Prepare this machine\".",
    "platform.now": "Target platform: {platform}.",
    "doctor.title": "Diagnose and understand",
    "doctor.machine": "Check this machine",
    "doctor.machine_hint": "Compilers, tools, buildable platforms",
    "doctor.explain": "Explain an error code",
    "doctor.explain_hint": "For a message like CH3002",
    "doctor.code": "Error code (for example CH3002)",
    "doctor.bad_code": "A code looks like CH followed by four digits.",
    "doctor.why": "Why was this rebuilt?",
    "doctor.why_hint": "Give a file or a target",
    "doctor.subject": "File or target",
    "doctor.history": "Build history",
    "doctor.history_hint": "The last builds, their time and result",
    "doctor.headers": "Costly headers",
    "doctor.headers_hint": "The headers whose change rebuilds the most",
    "git.title": "Git",
    "git.status": "Status",
    "git.status_hint": "Changes, last build, last quality check",
    "git.commit": "Commit",
    "git.commit_hint": "Runs the quality check on what changed, then commits",
    "git.message": "Commit message",
    "git.stage_all": "Include all modified files?",
    "git.push": "Push",
    "git.push_hint": "Runs the standard quality check, then pushes",
    "git.confirm_push": "Push to the remote now?",
    "git.hooks": "Install the Git hooks",
    "git.hooks_hint": "Run the quality check automatically",
    "cache.title": "Cache and cleaning",
    "cache.stats": "Cache size",
    "cache.stats_hint": "How much the build cache holds",
    "cache.gc": "Trim the cache",
    "cache.gc_hint": "Removes the least recently used files",
    "cache.clean": "Delete this project's build output",
    "cache.clean_hint": "The next build starts from scratch (the cache makes it fast)",
    "cache.confirm_clean": "Delete the build output of this project?",
    "cache.clear": "Empty the whole cache",
    "cache.clear_hint": "For every project on this machine",
    "cache.confirm_clear": "Empty the whole build cache?",
    "cache.uninstall": "What Charpente stores on this machine",
    "cache.uninstall_hint": "Shows it (removes nothing)",
    "cmd.equivalent": "The same command works in any terminal.",
    "cmd.done": "Done.",
    "cmd.interrupted": "Stopped.",
    "cmd.failed": "It did not succeed (exit code {code}).",
    "cmd.failed_tip": "Look at the message above; \"Diagnose and understand\" explains error codes.",
    "guide.title": "First steps",
    "guide.1": "1. Create a project: choose \"Create a new project\" and pick \"console\".",
    "guide.2": "2. Build it: \"Build\" compiles it. The first time, Charpente asks whether to trust the project file.",
    "guide.3": "3. Run it: \"Run\" starts the program.",
    "guide.4": "4. Change a source file and build again: only what changed is rebuilt.",
    "guide.5": "5. \"Test\" runs the tests; \"Quality check\" runs the checks you want before a commit.",
    "guide.6": "6. \"Target platform\" builds for other systems: Linux ARM, Android, the web...",
    "guide.7": "7. Every choice shows the command it runs: you can type the same in any terminal.",
    "guide.8": "More: docs/guide.md, or Charpente Studio for a graphical interface.",
    "help.title": "Help and shortcuts",
    "help.1": "Move: the up and down arrows. Choose: Enter, or the key shown beside the row.",
    "help.2": "Back: Esc or the left arrow. Leave: q at the main menu, or Ctrl+C.",
    "help.3": "Without arrow keys (a pipe, or CHARPENTE_CONSOLE=plain): type the number or letter, then Enter.",
    "help.4": "",
    "help.5": "The commands behind the menu:",
    "help.6": "  charpente build | run | test | dev         build, run, test, rebuild on change",
    "help.7": "  charpente init NAME --template T           a new project (charpente init --list)",
    "help.8": "  charpente doctor | platforms               what this machine can do",
    "help.9": "  charpente explain CH3002                   understand an error",
    "help.10": "  charpente check --level standard           quality check",
    "help.11": "  charpente studio | tui | shell             other interfaces",
    "help.12": "Every command has --help. The complete guide is docs/guide.md.",
    "help.13": "Plain output for scripts: charpente --help, or CHARPENTE_CONSOLE=off to never open this menu.",
    "tip.label": "Tip:",
    "tip.1": "Every choice shows the command it runs, so you learn the command line as you go.",
    "tip.2": "Press m to switch between Debug and Release.",
    "tip.3": "\"Diagnose and understand\" explains any CHxxxx error in plain words.",
    "tip.4": "Build for another system from \"Target platform\": Linux ARM, Android, the web.",
    "tip.5": "Prefer a graphical window? Press s to open Charpente Studio.",
    "tip.6": "Set CHARPENTE_CONSOLE=off if you would rather see the plain help.",
}

FR: Dict[str, str] = {
    "tagline": "le système de build C/C++",
    "bye": "À bientôt.",
    "footer.keys": "{ud} déplacer   Entrée choisir   la touche à côté d'une ligne : raccourci   Échap retour   Ctrl+C quitter",
    "footer.line": "Tapez le numéro ou la lettre d'une ligne, puis Entrée.   q : retour",
    "prompt.choice": "Votre choix : ",
    "prompt.unknown": "« {answer} » n'est pas dans la liste.",
    "prompt.required": "Une réponse est nécessaire ici.",
    "prompt.press_enter": "Appuyez sur Entrée pour revenir au menu...",
    "prompt.yes_no_default_yes": "[O/n]",
    "prompt.yes_no_default_no": "[o/N]",
    "ago.seconds": "il y a {n} s",
    "ago.minutes": "il y a {n} min",
    "ago.hours": "il y a {n} h",
    "ago.days": "il y a {n} j",
    "dash.title": "Où vous en êtes",
    "dash.folder": "Dossier",
    "dash.last": "Dernier build",
    "dash.mode": "Mode de travail",
    "dash.compiler": "Compilateur",
    "dash.native": "cette machine",
    "dash.targets": "{n} cible(s)",
    "dash.no_build": "aucun pour l'instant",
    "dash.succeeded": "réussi",
    "dash.failed": "échoué",
    "dash.no_project": "Aucun projet dans ce dossier",
    "dash.no_compiler": "aucun trouvé (choisissez « Préparer cette machine »)",
    "dash.untrusted": "Ce fichier de projet n'est pas encore approuvé : Charpente vous demandera avant de l'exécuter.",
    "dash.untrusted_short": "pas encore approuvé",
    "dash.error": "Le fichier de projet est illisible : {detail}",
    "dash.error_short": "erreur dans le fichier de projet",
    "dash.ambiguous": "Plusieurs fichiers de projet ici : {detail}",
    "group.start": "Démarrer",
    "group.more": "Plus",
    "group.build": "Construire et lancer",
    "group.project": "Votre projet",
    "group.tools": "Outils",
    "group.session": "Cette session",
    "item.create": "Créer un nouveau projet",
    "hint.create": "Choisissez un modèle (programme, bibliothèque, jeu, appli Android...)",
    "item.open": "Ouvrir un projet existant",
    "hint.open": "Aller dans un dossier qui contient un fichier .charpente",
    "item.setup": "Préparer cette machine",
    "hint.setup": "Repère ce qui manque (un compilateur...) et propose de le corriger",
    "hint.recommended": "Recommandé :",
    "item.check_machine": "Vérifier cette machine",
    "hint.check_machine": "Compilateurs et outils trouvés, plateformes constructibles",
    "item.guide": "Apprendre : les premiers pas",
    "hint.guide": "Cinq minutes pour un premier programme",
    "item.build": "Construire",
    "hint.build": "Compile le projet ({mode})",
    "item.run": "Lancer",
    "hint.run": "Construit si besoin, puis démarre un programme",
    "reason.cross_run": "Un programme construit pour {platform} ne peut pas s'exécuter sur cette machine.",
    "reason.fix_project": "Corrigez d'abord le fichier de projet (le message est plus haut).",
    "item.test": "Tester",
    "hint.test": "Construit et lance les tests",
    "item.watch": "Reconstruire à chaque changement",
    "hint.watch": "Surveille vos fichiers (Ctrl+C pour arrêter)",
    "item.targets": "Cibles et paquets",
    "hint.targets": "Ce que le projet construit ; bibliothèques à ajouter",
    "item.platform": "Plateforme visée",
    "hint.platform": "Actuelle : {platform}. Linux ARM, Android, web, microcontrôleurs...",
    "item.package": "Empaqueter",
    "hint.package": "Un zip, un installeur ou une appli Android à distribuer",
    "item.check": "Contrôle qualité",
    "hint.check": "Format, avertissements, secrets, tests avant un commit",
    "item.doctor": "Diagnostiquer et comprendre",
    "hint.doctor": "Expliquer une erreur, voir pourquoi quelque chose a été reconstruit, historique",
    "item.git": "Git",
    "hint.git": "État, commit contrôlé, push",
    "item.cache": "Cache et nettoyage",
    "hint.cache": "Libérer de l'espace disque, repartir de zéro",
    "item.studio": "Ouvrir Charpente Studio",
    "hint.studio": "L'interface graphique dans votre navigateur",
    "item.tui": "Interface plein écran (terminal)",
    "hint.tui": "Cibles et journal de build en direct (nécessite : pip install \"charpente[tui]\")",
    "item.mode": "Passer en {mode}",
    "hint.mode": "Actuel : {mode}. Release est optimisé, Debug sert à déboguer",
    "mode.now": "Le mode de travail est maintenant {mode}.",
    "item.lang": "Language: {other}",
    "lang.now": "Langue : français.",
    "item.help": "Aide et raccourcis",
    "hint.help": "Comment fonctionne ce menu, les commandes qu'il cache",
    "item.quit": "Quitter",
    "tag.unverified": "[non vérifié]",
    "create.title": "Créer un nouveau projet",
    "create.subtitle": "Choisissez de quoi partir. Tous les modèles se construisent avec les mêmes commandes.",
    "create.default_name": "mon-projet",
    "create.template": "Modèle : {template}",
    "create.name": "Nom du projet (lettres, chiffres, - et _)",
    "create.bad_name": "Commencez par une lettre ; ensuite lettres, chiffres, - ou _ seulement.",
    "create.exists": "{folder} existe déjà : choisissez un autre nom.",
    "create.summary": "Un projet « {template} » nommé « {name} » sera créé dans {folder}.",
    "create.confirm": "Le créer ?",
    "create.opened": "Projet « {name} » créé et ouvert. Essayez Construire, puis Lancer.",
    "open.title": "Ouvrir un projet existant",
    "open.other": "Un autre dossier...",
    "open.other_hint": "Tapez le chemin d'un dossier de projet",
    "open.path": "Dossier du projet",
    "open.not_a_folder": "« {path} » n'est pas un dossier.",
    "open.opened": "Vous travaillez maintenant dans {folder}.",
    "pick.target": "Quelle cible ?",
    "run.args": "Arguments du programme (Entrée pour aucun)",
    "watch.note": "Charpente reconstruira à chaque enregistrement d'un fichier. Ctrl+C pour revenir.",
    "check.title": "Contrôle qualité",
    "check.fast": "Rapide",
    "check.fast_hint": "Build, format, fichier de projet, secrets : quelques secondes",
    "check.standard": "Standard",
    "check.standard_hint": "Ajoute avertissements, analyse statique et tests",
    "check.strict": "Strict",
    "check.strict_hint": "Ajoute sanitizers, couverture, licences, audit des dépendances",
    "package.title": "Empaqueter en...",
    "package.zip": "Une archive zip du programme",
    "package.installer": "installeur",
    "package.installer_hint": "Un installeur pour ce système (nécessite son outil d'empaquetage)",
    "package.apk": "Une appli Android signée",
    "targets.title": "Cibles et paquets",
    "targets.list": "Voir les cibles",
    "targets.list_hint": "Ce que ce projet construit",
    "targets.none": "Les cibles du projet s'affichent une fois qu'il est approuvé et lisible.",
    "targets.search": "Chercher un paquet",
    "targets.search_hint": "fmt, spdlog, nlohmann_json...",
    "targets.query": "Que cherchez-vous",
    "targets.install": "Installer les paquets du projet",
    "targets.install_hint": "Télécharge et vérifie ce que le projet exige",
    "targets.kits": "Lister les kits",
    "targets.kits_hint": "Des ensembles de bibliothèques prêts à l'emploi",
    "targets.addkit": "Ajouter un kit au projet",
    "targets.addkit_hint": "Graphisme, jeu, réseau, embarqué...",
    "platform.title": "Plateforme visée",
    "platform.subtitle": "Votre choix s'applique à Construire, Tester, Empaqueter et Reconstruire.",
    "platform.checking": "Examen de ce que cette machine sait construire...",
    "platform.actions": "Actions",
    "platform.deploy": "Installer sur des appareils Android",
    "platform.deploy_hint": "Construit pour chaque téléphone ou émulateur connecté et lance l'appli",
    "platform.choose": "Construire pour",
    "platform.native": "Cette machine ({host})",
    "platform.native_hint": "Le choix par défaut",
    "platform.tier": "niveau {tier}",
    "platform.needs_toolchain": "Nécessite une chaîne d'outils : lancez « Préparer cette machine ».",
    "platform.now": "Plateforme visée : {platform}.",
    "doctor.title": "Diagnostiquer et comprendre",
    "doctor.machine": "Vérifier cette machine",
    "doctor.machine_hint": "Compilateurs, outils, plateformes constructibles",
    "doctor.explain": "Expliquer un code d'erreur",
    "doctor.explain_hint": "Pour un message comme CH3002",
    "doctor.code": "Code d'erreur (par exemple CH3002)",
    "doctor.bad_code": "Un code ressemble à CH suivi de quatre chiffres.",
    "doctor.why": "Pourquoi a-t-il été reconstruit ?",
    "doctor.why_hint": "Donnez un fichier ou une cible",
    "doctor.subject": "Fichier ou cible",
    "doctor.history": "Historique des builds",
    "doctor.history_hint": "Les derniers builds, leur durée et leur résultat",
    "doctor.headers": "En-têtes coûteux",
    "doctor.headers_hint": "Les en-têtes dont la modification reconstruit le plus",
    "git.title": "Git",
    "git.status": "État",
    "git.status_hint": "Changements, dernier build, dernier contrôle qualité",
    "git.commit": "Commit",
    "git.commit_hint": "Lance le contrôle qualité sur ce qui a changé, puis valide",
    "git.message": "Message du commit",
    "git.stage_all": "Inclure tous les fichiers modifiés ?",
    "git.push": "Push",
    "git.push_hint": "Lance le contrôle qualité standard, puis envoie",
    "git.confirm_push": "Envoyer vers le dépôt distant maintenant ?",
    "git.hooks": "Installer les hooks Git",
    "git.hooks_hint": "Lancer le contrôle qualité automatiquement",
    "cache.title": "Cache et nettoyage",
    "cache.stats": "Taille du cache",
    "cache.stats_hint": "Ce que contient le cache de build",
    "cache.gc": "Réduire le cache",
    "cache.gc_hint": "Supprime les fichiers les moins récemment utilisés",
    "cache.clean": "Supprimer les sorties de build de ce projet",
    "cache.clean_hint": "Le prochain build repart de zéro (le cache le rend rapide)",
    "cache.confirm_clean": "Supprimer les sorties de build de ce projet ?",
    "cache.clear": "Vider tout le cache",
    "cache.clear_hint": "Pour tous les projets de cette machine",
    "cache.confirm_clear": "Vider tout le cache de build ?",
    "cache.uninstall": "Ce que Charpente stocke sur cette machine",
    "cache.uninstall_hint": "L'affiche (ne supprime rien)",
    "cmd.equivalent": "La même commande fonctionne dans n'importe quel terminal.",
    "cmd.done": "Terminé.",
    "cmd.interrupted": "Arrêté.",
    "cmd.failed": "Cela n'a pas abouti (code de sortie {code}).",
    "cmd.failed_tip": "Lisez le message plus haut ; « Diagnostiquer et comprendre » explique les codes d'erreur.",
    "guide.title": "Les premiers pas",
    "guide.1": "1. Créez un projet : choisissez « Créer un nouveau projet » puis « console ».",
    "guide.2": "2. Construisez-le : « Construire » le compile. La première fois, Charpente demande s'il peut faire confiance au fichier de projet.",
    "guide.3": "3. Lancez-le : « Lancer » démarre le programme.",
    "guide.4": "4. Modifiez un fichier source et reconstruisez : seul ce qui a changé est recompilé.",
    "guide.5": "5. « Tester » lance les tests ; « Contrôle qualité » lance les vérifications voulues avant un commit.",
    "guide.6": "6. « Plateforme visée » construit pour d'autres systèmes : Linux ARM, Android, le web...",
    "guide.7": "7. Chaque choix affiche la commande qu'il lance : vous pouvez la taper dans n'importe quel terminal.",
    "guide.8": "Pour aller plus loin : docs/guide.fr.md, ou Charpente Studio pour une interface graphique.",
    "help.title": "Aide et raccourcis",
    "help.1": "Se déplacer : flèches haut et bas. Choisir : Entrée, ou la touche indiquée à côté de la ligne.",
    "help.2": "Retour : Échap ou flèche gauche. Quitter : q au menu principal, ou Ctrl+C.",
    "help.3": "Sans flèches (un tube, ou CHARPENTE_CONSOLE=plain) : tapez le numéro ou la lettre, puis Entrée.",
    "help.4": "",
    "help.5": "Les commandes derrière le menu :",
    "help.6": "  charpente build | run | test | dev         construire, lancer, tester, reconstruire au changement",
    "help.7": "  charpente init NOM --template T            un nouveau projet (charpente init --list)",
    "help.8": "  charpente doctor | platforms               ce que cette machine sait faire",
    "help.9": "  charpente explain CH3002                   comprendre une erreur",
    "help.10": "  charpente check --level standard           contrôle qualité",
    "help.11": "  charpente studio | tui | shell             d'autres interfaces",
    "help.12": "Chaque commande a --help. Le guide complet est docs/guide.fr.md.",
    "help.13": "Sortie simple pour les scripts : charpente --help, ou CHARPENTE_CONSOLE=off pour ne jamais ouvrir ce menu.",
    "tip.label": "Astuce :",
    "tip.1": "Chaque choix affiche la commande qu'il lance : vous apprenez la ligne de commande en chemin.",
    "tip.2": "Appuyez sur m pour passer de Debug à Release.",
    "tip.3": "« Diagnostiquer et comprendre » explique n'importe quelle erreur CHxxxx en clair.",
    "tip.4": "Construisez pour un autre système depuis « Plateforme visée » : Linux ARM, Android, le web.",
    "tip.5": "Vous préférez une fenêtre graphique ? Appuyez sur s pour ouvrir Charpente Studio.",
    "tip.6": "Définissez CHARPENTE_CONSOLE=off si vous préférez voir l'aide simple.",
}

TABLES = {"en": EN, "fr": FR}


def lookup(lang: str, key: str) -> str:
    """The text for `key`; a missing key shows the key itself (a test keeps that from happening), never an exception."""
    table = TABLES.get(lang, EN)
    if key in table:
        return table[key]
    return EN.get(key, key)
