"""Regenerates docs/events/ (JSON Schemas + a readable reference) from the event table.

    python tools/gen_event_docs.py          # rewrite the files
    python tools/gen_event_docs.py --check  # exit 1 if they are out of date (used by a test)
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from charpente.events import EVENT_TYPES, SCHEMA_VERSION  # noqa: E402
from charpente.events import schema as event_schema  # noqa: E402
from charpente.events.types import field_spec  # noqa: E402

OUT = ROOT / "docs" / "events"


def render() -> Dict[str, str]:
    files: Dict[str, str] = {}
    for name in EVENT_TYPES:
        files[f"{name}.schema.json"] = event_schema.dumps(event_schema.event_schema(name))
    files["event.schema.json"] = event_schema.dumps(event_schema.any_event_schema())

    lines = [
        "# Events reference / Référence des événements",
        "",
        "<!-- Generated by tools/gen_event_docs.py. Do not edit by hand. -->",
        "",
        f"Schema version: **{SCHEMA_VERSION}**. Every event is a JSON object with the envelope",
        "`schema_version, id, parent_id, timestamp, wall_time, session_id, type, payload`.",
        "`charpente build --output jsonl` prints one event per line; `event.schema.json` validates any of them.",
        "A field ending in `?` is optional. Adding an optional field is not a breaking change.",
        "",
    ]
    current = ""
    for name, spec in EVENT_TYPES.items():
        family = name.split(".", 1)[0]
        if family != current:
            current = family
            lines += [f"## {family}", "", "| Event | Payload |", "|---|---|"]
        fields = ", ".join(f"`{k}: {v}`" for k, v in spec.items())
        lines.append(f"| `{name}` | {fields} |")
        nxt = list(EVENT_TYPES).index(name) + 1
        if nxt >= len(EVENT_TYPES) or list(EVENT_TYPES)[nxt].split(".", 1)[0] != family:
            lines.append("")
    files["README.md"] = "\n".join(lines).rstrip() + "\n"
    for spec in EVENT_TYPES.values():
        for raw in spec.values():
            field_spec(raw)
    return files


def main(argv: "list[str]") -> int:
    files = render()
    if "--check" in argv:
        stale = []
        for name, text in files.items():
            path = OUT / name
            if not path.exists() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
                stale.append(name)
        extra = [p.name for p in OUT.glob("*.schema.json") if p.name not in files] if OUT.exists() else []
        if stale or extra:
            print(f"docs/events is out of date ({len(stale)} stale, {len(extra)} orphaned): "
                  f"run `python tools/gen_event_docs.py`", file=sys.stderr)
            return 1
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for stale_file in OUT.glob("*.schema.json"):
        stale_file.unlink()
    for name, text in files.items():
        (OUT / name).write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {len(files)} files to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
