"""Regenerates docs/errors.md from the message catalogue.

    python tools/gen_error_docs.py          # rewrite the file
    python tools/gen_error_docs.py --check  # exit 1 if it is out of date (used by a test)
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from charpente.i18n import en, fr  # noqa: E402

TARGET = ROOT / "docs" / "errors.md"

FAMILIES = {
    "1": "Loading the workspace / DSL",
    "2": "Toolchains and programs",
    "3": "Building",
    "4": "Packaging and command line",
    "5": "AI",
    "6": "Packages and dependencies",
    "7": "Modules",
    "8": "Quality gate and Git",
    "9": "Internal",
}


def render() -> str:
    lines = [
        "# Error catalogue / Catalogue des erreurs",
        "",
        "<!-- Generated by tools/gen_error_docs.py from charpente/i18n/{en,fr}.py. Do not edit by hand. -->",
        "",
        "Every error carries a stable code. `charpente explain CHxxxx` prints the same",
        "information in your language (`CHARPENTE_LANG=fr|en`). / Chaque erreur porte un code",
        "stable ; `charpente explain CHxxxx` affiche ces informations dans votre langue.",
        "",
    ]
    current = ""
    for code in sorted(en.CATALOG):
        if code[2] != current:
            current = code[2]
            lines += [f"## CH{current}xxx — {FAMILIES.get(current, '')}", ""]
        e, f = en.CATALOG[code], fr.CATALOG[code]
        lines += [
            f"### {code} — {e['title']}",
            f"*FR : {f['title']}*",
            "",
            f"- **Cause:** {e['cause']}",
            f"- **Fix:** {e['fix']}",
            f"- **Cause (FR) :** {f['cause']}",
            f"- **Correction (FR) :** {f['fix']}",
        ]
        if e.get("explain"):
            lines += ["", e["explain"]]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: "list[str]") -> int:
    text = render()
    if "--check" in argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print("docs/errors.md is out of date: run `python tools/gen_error_docs.py`", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
